# Enable kube-proxy replacement with Cilium's eBPF-based implementation
kubeProxyReplacement: true

# IP Address Management
ipam:
  mode: cluster-pool

# Hubble Configuration
hubble:
  enabled: true
  relay:
    enabled: true
    listenAddress: ":4245"
    nodeSelector:
      node-role.kubernetes.io/monitoring: "true"  # Hubble Relay runs on monitoring nodes
  ui:
    enabled: true
  metrics:
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - icmp
      - http

# Prometheus Metrics
prometheus:
  enabled: true

# Cilium DaemonSet Configuration
nodeSelector: {}  # Allow Cilium DaemonSet to run on all nodes

# Operator Configuration
operator:
  enabled: true
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"  # Run the Cilium Operator on the control-plane node

# Enable eBPF Features
bpf:
  masquerade: true  # Enable eBPF-based masquerading
  nodePort:
    enabled: true   # Use eBPF for Kubernetes NodePort services
    bindProtection: true
